name: store_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  rxdart: ^0.27.7
  provider: ^6.0.5
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.5.0
  google_maps_place_picker_mb: ^3.0.1
  image_picker: ^1.0.4
  intl_phone_number_input: ^0.7.3
  gap: ^3.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  rive: ^0.13.4
  lottie: ^2.6.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  timeago: ^3.5.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  onesignal_flutter: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  # flutter_gen_runner: ^5.0.3
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3
  analyzer: ^6.2.0

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/sounds/
    - .env

# flutter_gen:
#   output: lib/gen/
#   line_length: 80
#   integrations:
#     image: true
#     flutter_svg: true
#     rive: true
#     lottie: true

dependency_overrides:
  win32: ^3.1.4